### ISSUE TITLE
Refactor Chunk2DocRankers

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2075]
# Maintenance ticket

<p></p>

For further information check the #triage-rankers slack channel. 

# Acceptance Criteria

- This ticket is done when:  Chunk2DocRankers has been refactored,  moving most of the logic to Driver keeping a clean interface for the Executor. 

- This ticket is done when: dependencies on batching is passed to executors (performance enhancement for every executor (not just for Crafters). 

<p></p>

# Subtasks

- [x]  Pass the PR #2113 
- [x]  Remove TFIDF and BM25Rankers from the jina-hub
- [x]  Refactor BiMatchRanker and SimpleAggregateRanker to not depend on functions that have disappeared.
- [x]  Enable batching for Match2DocRankers (PR #2145 )
- [x] Look for potential optimizations in Chunk2DocRankers related to numpy array handling (PR #2163

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7057669

**Comment by FionnD** [comment]
All PR are merged, I am closing this issue
