### ISSUE TITLE
General Driver Optimization [batching]

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2097]
# Feature Request 

Allowing batching potentially for every Executor. This will improve future performance long-term. 

<p></p>

# Acceptance Criteria

- This ticket is done when: all Executors allow for batching. 

- This ticket is done when: relevant docstrings have been updated. 

<p></p>

# SubTasks

- [x] PR #1950 is merged as dependency
- [x] Make sure Encoder, MultiModalEncoder, Classifier already have batching capability
- [x] Pass the PR #2098. 
- [x] Go driver per driver, allowing batching to each of them. For each of them go to its executors in the hub add @single decorator added in #2098.
- [ ] For each of the drivers in previous step, refactor its executors that can be batched into using batch decorators

Special cases:
- [ ] Make sure query is batched also for `Indexers` (Vector and KV)
- [ ] Clarify batching in Rankers (that could be left to have it handled in #2075)
- [ ] Maybe Evaluators would need to iterate on their `single` decorator to batch tuples

Wrap-up work:
- [x] Come with a good default for batching meta
- [ ] Add clear documentation both in core and hub into how and when to use @batching or @single decorator

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7100934

**Comment by FionnD** [comment]
I added two futher tickets 
https://github.com/jina-ai/jina/issues/2157 
https://github.com/jina-ai/jina/issues/2156
