### ISSUE TITLE
Rename DocumentSet -> DocumentList

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/jina#2228]
**Describe the feature**
The `jina.types.sets.document.DocumentSet` is acutally a list. The same is true for all other modules/classes in `jina.types.sets`. They should be renamed consistently to `...List` including the package name `jina.types.lists`. While doing this, the old names should still stay until Jina 2.0.0 and be deprecated via the deprecated decorator.

**Subtasks**

- [ ] move all modules inside `jina.types.sets` to `jina.types.lists`
- [ ] Prerequisite for the next: add a new deprecate decorator for classes (see `deprecated_alias` to get an idea what should be logged)
- [ ] add the old names back to `jina.types.sets` by using the moved modules/classes from `jina.types.lists` and deprecate them directly with the removing announcement with `Jina 2.0.0`
- [ ] Fix all mentions inside our documentations
- [ ] Follow-up: switch all modules in the Hub to the new naming
- [ ] Follow-up: switch all examples to the new naming

**Comment by FionnD** [comment]
Good issue for new hire
