### ISSUE TITLE
Move integration tests to 2.0 

### ISSUE THREAD

**Issue by FionnD** [jina-ai/jina#2479]
**Describe the feature**
As we move towards 2.0, we need to redo each of our current integration tests and update them to the new codebase. 

Integration tests in `1.x`

When moving tests from `issues` to somewhere else, keep the issue ID in the docstring of the test.

TO WORK ON THIS

1. Put your name on a task you pick
1. Open a PR
1. Add the PR next to the checkbox
1. Tick the checkbox once the PR is done

(check first item below)

* [x] crud. Basic: https://github.com/jina-ai/jina/pull/2501 cristianmtr 
  * [x] test workspace usage in CRUD (serialization) https://github.com/jina-ai/jina/pull/2521
  * [x] rename to just `crud` https://github.com/jina-ai/jina/pull/2521
  * [x] test chunks in CRUD https://github.com/jina-ai/jina/pull/2521
* [x] **rest usage in `integration/flow`** cristianmtr https://github.com/jina-ai/jina/pull/2525
* [x] crud_corrupted_docs
  * [x] to be removed
  * [x] **mime type detection under tests/docs** cristianmtr  https://github.com/jina-ai/jina/pull/2531
* ~[ ] debug -- to be moved to hub~
* [x] doccache -- only on 'r' level https://github.com/jina-ai/executor-indexers/pull/21
* [x] dump -- moved to hub integration https://github.com/jina-ai/indexers/pull/8 cristianmtr 
* [x] eval_flow. To be kept. Tests hanging pods for evaluation (name has changed: `test_inspect_pods_flow.py`)
* [x] evaluation. 
  * [x] one part move to Hub, about the Evaluator @JoanFM 
  * [x] groundtruth test in core, check to see if you can pass GroundTruths to inputs #2520 maximilianwerk 
* ~[ ] executors_batching~. We don't have batching anymore. Responsibility of Executors
* ~[ ] executors_generic~. Tested in other places.
* [x] gateway_non_blocking -- added
* [x] high_order_matches -- added
* [x] hub_usage -- added
* [x] incremental_indexing -- to be added to DocCache in Hub https://github.com/jina-ai/executor-indexers/pull/21
* **issues**
  * ~[ ] github_1072~
  * [x] **check if filter is tested on DA** cristianmtr https://github.com/jina-ai/jina/pull/2535
  * [x] check if parameters are passed to f.post #2520 maximilianwerk
  * ~[ ] github_1229~
  * [x] **check if docs_matrix is tested in Tail** #2537 maximilianwerk beware: Two test cases needs complicated fixing!
  * move MatchMerger to hub with travers path param -- added to https://github.com/jina-ai/internal-tasks/issues/92
  * [x] **github_1468 -- to investigate** #2537
  * ~[ ] github_1545~ -- unnecessary
  * [x] **github_1546. To be added. Tests order of imports in pymodule** #2536  maximilianwerk 
  * [x] github_1684 -- to be added to NpIndexer in hub https://github.com/jina-ai/indexers/pull/10 maximilianwerk 
  * [x] **github_1861 -- test that if an exception is raised in init everything is closed properly** #2532 maximilianwerk 
  * [x] github_2103
  * [x] **github_2254 -- test that siblings from chunks are updated. Right now they need to be set manually. Might be remove and moved to tags. Siblings used to be updated from `.extend`** #2543 maximilianwerk 
  * ~[ ] github_2295~. Serialization is Executor based
  * ~[ ] github_2320 -- to be added to Hub for BinaryPbIndexer~ adapted to test growth
  * [x] **github_867 -- expensive closing of Executor is not interrupted by Flow. To be moved to Flow tests** cristianmtr https://github.com/jina-ai/jina/pull/2545
  * ~[ ] github_929 -- Will not be kept, but we should add serialization to the stress test jacobowitz deepankarm also move to BinaryPbIndexer in hub~
  * ~[ ] github_969~ -- Removed. But maybe should be put in a museum?
  * ~[ ] github_976~ Removed
* ~[ ] level_depth~. This is covered by multires example
* [x] logging -- added
* ~memmap~ -- Did only test, that the numpy indexer does not crash and logged memory usage. Nice as a blueprint for future memory logging, but otherwise useless. Will be deleted.
* [x] **merge_pass -- to be adapted. First test in core,** other in hub under MatchMerger
* [x] **mime -- add more mime type assertions to `tests/unit/types/document/test_converters.py`** https://github.com/jina-ai/jina/pull/2531
* ~[ ] multimodal~ -- covered in test document multimodal
* [x] optimizers. To be adapted #2519  maximilianwerk 
* [x] ranker_training. To be moved to Hub @bwanglzu **https://github.com/jina-ai/executor-lightgbm-ranker/pull/1**
* ~[ ] ref_indexer~ -- Potentially not implemented again
* [x] **rolling_update -- no actual data (double check again if more tests/as fsertions need to be added)** cristianmtr  https://github.com/jina-ai/jina/pull/2546
* [x] sharding -- to be moved to Hub @cristianmtr https://github.com/jina-ai/indexers/pull/13
* [x] sparse_pipeline -- added

**Comment by cristianmtr** [comment]
Some comments:

`crud` -- I guess here we would be testing on dummy Executors in the core?

`dump` -- This is there, but it's the `DocumentArray.save` implementation. The plan is to have the hub module of PSQLIndexer be the one that implements the exports and imports. Then people needing those would need to import that module.

**Comment by FionnD** [comment]
Note https://github.com/jina-ai/jina/issues/2530 I know they are different, but maybe someone could add 2530 while working on this issue?

**Comment by cristianmtr** [comment]
@CatStark can we close this one?
