### ISSUE TITLE
Move Indexers to separate 2.0 Executor Repo

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/jina#2560]
Executors will become semi-separate repositories beginning from 2.0. Thus, we should move indexer to https://github.com/jina-ai/indexers and update them there to version 2.0 accordingly.

Clean up / documentation tasks:

* [x] Write a short Readme about usage https://github.com/jina-ai/executor-indexers/pull/28
* [x] rewrite/remove `manifest.yml` (to be decided) https://github.com/jina-ai/executor-indexers/pull/28
* [x] checking config files https://github.com/jina-ai/executor-indexers/pull/30
* [x] refactor traversal paths https://github.com/jina-ai/executor-indexers/pull/25
* [x] integration tests that involve multiple Indexers at repo top-level, under `tests/integration`

* move to 2.0 Executor API
* include `traversal_paths` as a parameter
* ~Run the tests locally for now~

The following indexers needs to be moved:

* [x] `query/vector/NumpyIndexer` 
* [x] `dbms/PostgreSQLIndexer` cristianmtr https://github.com/jina-ai/indexers/pull/8/
* [x] `dump/dump.py` (`jina.commons`) + integration tests cristianmtr https://github.com/jina-ai/indexers/pull/8/
* [x] `compound/query/NumpyPostgresIndexer` https://github.com/jina-ai/indexers/pull/8/ cristianmtr 
* [x] `query/vector/AnnoyIndexer` Yongxuanzhang https://github.com/jina-ai/indexers/pull/11
* [x] `compound/NumpyFileQueryIndexer`
* [x] `query/keyvalue/FileQueryIndexer`
* [x] `dbms/FileDBMSIndexer` https://github.com/jina-ai/executor-indexers/pull/18 @cristianmtr 
* [x] `query/vector/FaissIndexer` @cristianmtr 
* more integration tests
* [x] assert FileDBMSIndexer size does not grow with update https://github.com/jina-ai/executor-indexers/pull/23
* [x] potentially gets a new LMDB backend in the future https://github.com/jina-ai/executor-indexers/pull/24

Missing suitable integration tests from #2479 should be moved accordingly.

Finally: Use one of them in examples.

**Comment by theUnkownName** [comment]
For this ticket it will be @maximilianwerk and @cristianmtr as said in Slack right?

**Comment by JoanFM** [comment]
Pleas, if possible add an `endpoint` to extract `vector` given a `document` id.  This can be useful to have a `recommendation` flow

**Comment by maximilianwerk** [comment]
> Pleas, if possible add an `endpoint` to extract `vector` given a `document` id. This can be useful to have a `recommendation` flow

I see your motivation and would say: Let's see. For Numpy that should be possible. I can't judge yet for Annoy and Faiss.

**Comment by JoanFM** [comment]
`Annoy` supports `get_item_vector`

and `Faiss` supports `index.reconstruct(id)`

**Comment by alexcg1** [comment]
> Use one of them in examples

Which is the most commonly used by our community? Faiss? Annoy? Best to use the most popular because:

- Better for SEO (our example might come up)
- Users recognize it
- Less work for users to adapt it
