### ISSUE TITLE
Embeddings optimization

### ISSUE THREAD

**Issue by CatStark** [jina-ai/jina#3170]
- [x] need a .embeddings `setter`. It should have same logic & constraints like its `getter` #3190 
- [x] `jina/types/arrays/memmap.py:L448-455` need a change to use .embeddings -> Done in #3184 
- [ ] The same .`embeddings` optimization should be applied to .`blobs` (when content is `blob`) -> #3198 

Details in slack [thread](https://jinaai.slack.com/archives/C01FLNY3B4K/p1628975458092800)

**Comment by davidbp** [comment]
Embeddings setter:  https://github.com/jina-ai/jina/pull/3190
