### ISSUE TITLE
Remove Optionality of `DocumentArray` for `Executors` requests.

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#3466]
**Describe the feature**
In `DataRequestHandler` it was decided to add `Optionality` to `DocumentArray` when `DocumentArrayProto` comes empty in the request.

This leads to every `executor` needing to do:
```python
if not docs:
   return
```

This is a problem, and is quite noisy.

The code that needs to be removed is tjhe check on the length of `DocArray`.:
 
```python
    # to unify all length=0 DocumentArray (or any other results) will simply considered as None
    # otherwise the executor has to handle DocArray(0)
    if len(result):
        return result
```

**TODO**

- [ ] Remove the checks from the code
- [ ] Adapt and pass tests
- [ ] Check Documentation, and make sure it is clear that `DocumentArray` is not `Optional` in the signature of `Executors`. 

**Follow-up**

- [ ] Executors do not need to consider `DocumentArray` as `Optional`
- [ ] Examples and so on should to the best of the capacity not show this

**Comment by CallmeMehdi** [comment]
Hello @JoanFM I would like to take this issue. If possible I will create a PR then link this to it.

**Comment by CatStark** [comment]
Hi @CallmeMehdi great that you are interested on this! Could you link the PR to this issue when you start working on it please?

**Comment by CallmeMehdi** [comment]
@CatStark Yes surely, as soon as I finish an initial PR I will link it here
