### ISSUE TITLE
add distribuetd test for scale method

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#3911]
**TODO**
In order to support `scale` endpoint for Remote Flows and Pods, JinaD needs to:

- [ ] Clarify the Update endpoint and accept different parameters depending on the `kind` of update operation
- [ ] Add a new UpdateOperation scale
- [ ] Unittest the `update` methods
- [ ] Add distributed tests for scale endpoint. (Remote Flow, and local flow with remote executors)

**Comment by JoanFM** [comment]
Blocked until #3816 is merged
