### ISSUE TITLE
Implement all the metrics that we want to expose for release

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#4589]
This issue is about implementing the following metrics that will be supported by core for the Flow

- [x]  `process_request_seconds` (Executor delay on requests method): Applies only to workers. Should track which method is called (https://github.com/jina-ai/jina/pull/4635)
- [x]  `receiving_request_seconds`: From receiving a request to responding to the caller. Applies to Gateway, head, worker  
            - [x] gateway (https://github.com/jina-ai/jina/pull/4638 ) 
            - [x] head  (https://github.com/jina-ai/jina/pull/4638 ) 
            - [x] worker ( https://github.com/jina-ai/jina/pull/4526) 
          
- [x]  `sending_request_seconds`: From sending to a Pod to receiving.
            - [x] gateway ( https://github.com/jina-ai/jina/pull/4526) 
            - [x] head ( https://github.com/jina-ai/jina/pull/4526) 

- [x]  `document_processed_total`: at the worker, just a counter (https://github.com/jina-ai/jina/pull/4672)

- [x] rename metrics according to https://prometheus.io/docs/practices/naming/ (https://github.com/jina-ai/jina/pull/4636)

ref to internal design document https://docs.google.com/document/d/17NqWFh8Q9bkOkHw3et-_ghWkl_mISu2AjE5LC3dsp3M/edit
