### ISSUE TITLE
Implement all the metrics that we want to expose post release

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#4731]
Follow up of https://github.com/jina-ai/jina/issues/4589

- [ ] Number of fails: How many requests failed, exception type etc 
- [x] Request size: In bytes of the request object https://github.com/jina-ai/jina/pull/4789
- [ ]  Number of Clients connected: gateway only 
- [x] Number of pending requests: gateway only https://github.com/jina-ai/jina/pull/4789
