### ISSUE TITLE
Healthcheck endpoints for server.

### ISSUE THREAD

**Issue by MrBeeMovie** [jina-ai/jina#4741]
Are there standard healthcheck endpoints as part of the server for both http and grpc? If not it would make it much easier to register a healthcheck for a docker container if this was added. Thank you for your hard work!

**Comment by JoanFM** [comment]
Hey @MrBeeMovie,

How are you deploying Clip as a Service? Is it locally, on Kubernetes or with docker compose?

**Comment by MrBeeMovie** [comment]
> Hey @MrBeeMovie,
> 
> How are you deploying Clip as a Service? Is it locally, on Kubernetes or with docker compose?

I am running on local. I want a direct way to check the server status because I am using the HEALTHCHECK keyword in the dockerfile. It would be useful to be able to curl localhost:port/healthcheck or something similar so I don't have to setup the clip-client and then call profile.

**Comment by MrBeeMovie** [comment]
> in CaS, client provide a `profile` interface https://clip-as-service.jina.ai/user-guides/client/#profiling that allows you to "healthcheck" the server.
> 
> I guess your question is more about how to directly & natively check server status from K8s/cloud-native ecosystem. Jina core should have provided the interface, maybe it needs to be documented. Will move this issue to the core for better discussion.

Yeah, sorry if I missed this in the documentation. I will look over it again. I am looking for a way to curl an endpoint from clip-server so that I do not have to setup clip-client to check the server status. If you can direct me towards the appropriate documentation that would be great. I understand that this is probably more related to Jina core but maybe you can include in the documentation under [plain http requests](https://clip-as-service.jina.ai/user-guides/client/#profiling) if this endpoint does exist. Thank you for your time!

**Comment by deepankarm** [comment]
@MrBeeMovie An health check endpoint for `protocol: http` exists already at `GET /`.

![image](https://user-images.githubusercontent.com/9050737/166641584-1a51e55a-4299-44d2-9f4d-5032d26f0564.png)

But you're right, we need to add it for `protocol: grpc`. An example usecase is, AWS ALB expects a path to be defined for health check (defaults to `/AWS.ALB/healthcheck`). It also supports a [response code](https://grpc.github.io/grpc/core/md_doc_statuscodes.html), which defaults to `12 (UNIMPLEMENTED)`. This path should be provided by `jina` & the response code should be `0 (OK)`. 

![image](https://user-images.githubusercontent.com/9050737/166642225-a36a1e17-070b-4946-8427-72975f93c811.png)

The gRPC health check protocol is documented [here](https://github.com/grpc/grpc/blob/master/doc/health-checking.md#grpc-health-checking-protocol).

**Comment by jacobowitz** [comment]
The scope of this issue is to implement a grpc health check for every Jina pod as [defined by their specification](https://github.com/grpc/grpc/blob/master/doc/health-checking.md#grpc-health-checking-protocol).
This new endpoint should eventually replace the old ControlRequest STATUS endpoint. For compatibility reasons, I would keep the old endpoint around for a little bit though.

- [ ] Implement the new grpc health check
- [ ] Switch over Jina implementation to use the new endpoint, instead of the STATUS endpoint
- [ ] Document how the new health check can be used (and also mention the existing http version)
- [ ] Create and schedule an issue for the removal of the STATUS endpoint

**Comment by JoanFM** [comment]
Also @jacobowitz from this ticket, should we open a ticket about creating a `ready_check` that can be called from client?

**Comment by jacobowitz** [comment]
no, I think that is unrelated and should be done [here](https://github.com/jina-ai/jina/issues/4730)

**Comment by JoanFM** [comment]
Hey @MrBeeMovie ,

In #4824 and in v3.6.0 you can see the new healthcheck endpoints
