### ISSUE TITLE
Catch up with the missing metrics in the Head

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#5184]
# Context

Some metrics are only available in the gateway and not in the head this should not be the case.

List of metrics impacted:

- [ ] jina_number_of_pending_requests
- [ ] jina_successful_requests_total
- [ ] jina_failed_requests_total

See the docs for the available metrics : https://docs.jina.ai/fundamentals/flow/monitoring-flow/
